FROM openjdk:11
LABEL maintainer="Digirati <opensource@digirati.com>"

USER root

RUN apt-get clean && apt-get update && apt-get -y upgrade \
    && apt-get install -y python python-pip \
    && add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable" \
    && apt-get update && apt-get -y install docker-ce

RUN pip install pre-commit

USER gradle
