FROM gradle:5.4.1-jdk11
LABEL maintainer="Rob March <rob.march@digirati.com>"

RUN apt-get clean && apt-get update && apt-get -y upgrade \
    && apt-get install -y python python-pip

RUN pip install pre-commit
