openapi: 3.0.0
info:
  title: "API"
  version: "1.0.0"
  contact:
    name: Digirati
    email: opensource@digirati.com
    url: https://github.com/digirati-co-uk/digirati-taxonomy-manager
  description: |
    This specification covers all actions and operations required to create and manage a SKOS taxonomy.

    __Data Model__ 

    The taxonomy management API is architected as a set of RESTful JSON-LD resources that can be manipulated and traversed
    by a client. All URIs present in an API response from the management system **MUST** be dereferencable as SKOS resources.
    The operations listed below specify the actions that can be performed on the collection of taxonomies that TaxMan hosts.

    __Localization__
    
    The SKOS data model puts a large focus on localization of taxonomies, and the API should respect and export this.
    Any property with a type of rdfs:PlainLiteral should be marshalled to JSON with an embedded language map, even when
    only one other label exists for the property.

    <small>Conforming Response</small>
    ```json
    {
      "@id": "<x>",
      "skos:prefLabel": [
        {
          "@lang": "en",
          "@value": "test"
        }
      ]
    }
    ```
      
    <small>Non-conforming Response</small>
    ```json
    {
      "@id": "<x>",
      "skos:prefLabel": "test"
    }
    ```

    __Deferencing Resources__

    It **MUST** be possible to deference all resources that are referenced by IRI. For example, when a GET request to a _skos:Concept_ 
    provides a list of IRIs that are _broader_ or _narrower_ concepts then each of those elements should have an IRI that dereferences to
    a taxonomy management endpoint. This is in addition to providing all [Lexical labels](https://www.w3.org/TR/skos-reference/#labels) for each resource


tags:
  - name: concept-scheme
    description: Operations executed on whole taxonomies.
  - name: concept
    description: Operations executed on single concepts.
paths:
  /0.1/concept-scheme/{scheme}/concept/{concept}:
    parameters:
      - $ref: '#/components/parameters/scheme'
      - $ref: '#/components/parameters/concept'
    put:
      tags:
        - concept
      description: Update an existing skos:Concept.
      requestBody:
        description: The updated skos:Concept resource to be saved.
        content:
          'application/ld+json;profile="http://www.w3.org/2004/02/skos/core.jsonld"':
            example:
              $ref: './samples/concept.json'       
      responses:
         '204':
            description: Update was successful, and the skos:Concept is unchanged from the request body.              

  /0.1/concept-scheme/{scheme}/concept:
    parameters:
      - $ref: '#/components/parameters/scheme'
    post:
      tags:
        - concept
      summary: Create a new Concept.
      operationId: addConceptToScheme
      requestBody:
        description: A skos:Concept resource.
        content:
          'application/ld+json;profile="http://www.w3.org/2004/02/skos/core.jsonld"':
            example:
              $ref: './samples/concept.json'
      responses:
        '201':
          description: The newly created skos:Concept resource, with the additional skos:inScheme property for the new parent.
          content:
            'application/ld+json;profile="http://www.w3.org/2004/02/skos/core.jsonld"':
              example:
                $ref: './samples/concept-in-scheme.json'

  /0.1/concept-scheme/{scheme}:
    parameters:
      - $ref: '#/components/parameters/scheme'
    get:
      summary: Get a ConceptScheme
      tags:
        - concept-scheme
      responses:
        '404':
          $ref: '#/components/schemas/error'
        '200':
          description: |
            A skos:ConceptScheme resource, containing embedded links to the skos:Concept entries
            appearing within it. Any embedded data (such as a `skos:Concept`, or a linked `skos:Collection`)
            will contain presentational properties as defined by _Lexical Labels_ in the SKOS specification.
          content:
            'application/ld+json;profile="http://www.w3.org/2004/02/skos/core.jsonld"':
              example: 
                $ref: samples/concept-scheme.json

  /0.1/concept-scheme/:
    post:
      summary: Create a ConceptScheme
      tags: 
        - concept-scheme
      operationId: createConceptScheme
      requestBody:
        description: "A representation of the ConceptScheme being created."
        content:
          'application/ld+json;profile="http://www.w3.org/2004/02/skos/core.jsonld"':
            example:
              $ref: './samples/concept-scheme.json'
          multipart/form-data:
            example:
              $ref: './samples/concept-scheme.xml'
      responses:
        '201':
          description: The newly created ConceptScheme resource.
          links:
            addConcept:
              operationId: addConceptToScheme
              parameters:
                scheme: $response.body#/@id
          content:
            'application/ld+json;profile="http://www.w3.org/2004/02/skos/core.jsonld"':
              example: 
   
components: 

  responses:
    notFound:
      description: The specified resource was not found
      content:
        'application/problem+json':
          schema:
            $ref: '#/components/schemas/error'
    unauthorized:
      description: Unauthorized
      content:
        'application/problem+json':
          schema:
            $ref: '#/components/schemas/error'

  schemas:
    error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message

  parameters:
    concept:
      name: concept
      in: path
      description: Concept identifier. The unique identifier of the Concept being addressed (not its IRI).
      schema:
        type: string
    scheme:
      name: scheme
      in: path
      description: Scheme identifier. The unique identifier of the ConceptScheme being addressed (not its IRI).
      schema:
        type: string

